### ISSUE TITLE
中间的弹窗炸了

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#103]
[松饼Bug]
ID: xmt
期望现象：白筑幕能够察觉到对手拆掉对子的向听倒退
实际现象：白筑幕一直到终局都没有反馈任何信息
复现步骤：使用白筑幕
截图：
![qq 20180306152250](https://user-images.githubusercontent.com/36924637/37019184-5148bd5a-2152-11e8-9a5c-ca527a9e1918.jpg)
![qq 20180306152256](https://user-images.githubusercontent.com/36924637/37019186-521998bc-2152-11e8-920d-f76c4ff25ad8.jpg)
环境：0.9.2,Android 6.0.1
和duang一样，可能是中间的弹窗炸了。

**Comment by rolevax** [comment]
200
