### ISSUE TITLE
在查看牌谱和修改背景时允许使用后退键返回

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#122]
[已有功能改良]
ID: xmt
已有不足：在查看牌谱和修改背景时无法通过后退键返回
改良方案：在查看牌谱和修改背景时允许使用后退键返回
参考作品：无

**Comment by rolevax** [comment]
与 #64 重复

**Comment by xiaomiantan3** [comment]
我说的是是查看牌谱和修改背景时，不是对战时，对战时已经可以返回了

**Comment by rolevax** [comment]
100
