### ISSUE TITLE
薄墨初美AI可能不做小四喜

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#125]
[能力改良]
ID: TerryHu
角色：薄墨初美
期望表现：薄墨初美AI会放过小牌做小四喜
实际表现：薄墨初美AI不会放过小牌
原作依据：按照原作逻辑
偶然排除：
![2018-03-08 13-17-42](https://user-images.githubusercontent.com/28784198/37134375-3c484bb4-22d3-11e8-8672-85782592e91d.png)

**Comment by rolevax** [comment]
- AI行为不属于能力改良
- 关于AI，现在的方针是改良整体设计，而不是封堵一个个特例

**Comment by humuyan** [comment]
> AI行为不属于能力改良

感觉这个没有明确的分类

> 关于AI，现在的方针是改良整体设计，而不是封堵一个个特例

不同人物的AI应该要适应不同人物能力

**Comment by rolevax** [comment]
以前有个AI的分类，现在因为不太需要所以删了

> 不同人物的AI应该要适应不同人物能力

现在的问题是“如何适应”，而不是“适应什么”

**Comment by humuyan** [comment]
那应该强制薄墨初美胡小四喜吧

**Comment by rolevax** [comment]
如何强制？

**Comment by humuyan** [comment]
就是在坐北家将鬼门牌置于鬼门方位后，只要巡目足够，放弃非小四喜的和牌

**Comment by rolevax** [comment]
如何放弃？

**Comment by humuyan** [comment]
比如截图中的情况，和牌不是小四喜就见逃

**Comment by rolevax** [comment]
- 只要不见逃，就一定能和役潢吗？
- 自己是大top也见逃吗？

**Comment by humuyan** [comment]
这些问题都和具体的场况判断有关。
但是不同人物的AI应该要根据自己的技能作出更好的选择，之前截图中的点差情况显然是做小四喜更有利。
对于基础雀力方面的问题是需要改良整体设计，这里我建议每个人物添加一个函数，在AI作出选择前先运行这个函数，使AI作出一些与自己能力有关的特殊决策。

**Comment by rolevax** [comment]
太笼统了

> 这里我建议每个人物添加一个函数

自己试试看看，很多问题光靠想象是不够的

**Comment by humuyan** [comment]
难道不是直接写一个薄墨初美的`think`么

**Comment by rolevax** [comment]
……
