### ISSUE TITLE
牌谱视角未重置

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#138]
[松饼Bug]
ID: xmt
期望现象：切换视角时人物正常切换
实际现象：切换视角时人物未能正常切换
复现步骤：先打开牌谱切换视角1，在返回重新打开牌谱，仍然是视角1，但人物和视角0匹配
截图：
![qq 20180309180417](https://user-images.githubusercontent.com/36924637/37202032-5bef5ec0-23c4-11e8-9227-2260b1a163e2.jpg)
![qq 20180309180422](https://user-images.githubusercontent.com/36924637/37202034-5d52dd3c-23c4-11e8-8d32-32f775dd496f.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
