### ISSUE TITLE
在牌效练习中按返回键会返回上一级的上一级

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#143]
[松饼Bug]
ID: xmt
期望现象：在牌效练习中按返回键会返回上一级
实际现象：在牌效练习中按返回键会返回上一级的上一级
复现步骤：进入牌效练习，按返回键
截图：无法通过截图体现
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
