### ISSUE TITLE
在牌效练习中立直不显示第一张舍牌

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#144]
[松饼Bug]
ID: xmt
期望现象：在牌效练习中立直会横置第一张舍牌
实际现象：在牌效练习中立直不显示第一张舍牌
复现步骤：在牌效练习中立直
截图：
![qq 20180310202409](https://user-images.githubusercontent.com/36924637/37242246-09dab9c6-24a1-11e8-9db9-306203df1947.jpg)
![qq 20180310202404](https://user-images.githubusercontent.com/36924637/37242286-b0c8a478-24a1-11e8-8933-fbc151955b5b.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
