### ISSUE TITLE
牌谱动画效果

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#145]
[已有功能改良]
ID: xmt
已有不足：查看牌谱时吃碰杠自摸荣和不会出现对局时显示的图标动画
改良方案：查看牌谱时吃碰杠自摸荣和时添加图标动画
参考作品：无

**Comment by rolevax** [comment]
100

**Comment by rolevax** [comment]
牌谱播放器还有很多东西要做

- 标出最后一张弃牌
- 前进/后退时显示相应动画
- 进度条
- 自摸切/手切区分
- 显示/隐藏他家手牌
