### ISSUE TITLE
查看牌谱时无法左右滑动进退

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#149]
[松饼Bug]
ID: xmt
期望现象：查看牌谱时左右滑动进退
实际现象：查看牌谱时无法左右滑动进退，按中间会使牌山在最前端显示
复现步骤：查看牌谱时放大缩小手牌可能会复现
截图：
![qq 20180311130409](https://user-images.githubusercontent.com/36924637/37249959-da46af30-252c-11e8-9667-fd045c9f1859.jpg)
环境：0.9.2,Android 6.0.1
这可能是放大缩小手牌和左右滑动冲突导致，并且在此状态点“已阅”退出后重新打开并不会重置。

**Comment by rolevax** [comment]
+100
