### ISSUE TITLE
关于玄的宝牌控制

### ISSUE THREAD

**Issue by chouqiandaren** [rolevax/mjpancake#162]
[松饼Bug]
ID: 羡ましい
期望：AI玄未主动舍去宝牌时，其他人摸不到宝牌
实际：如图（赤4规则）
复现步骤：按序选用怜，大星淡，上重漫，玄，在玄坐庄时大星淡未双立直、玄未完全收集到赤宝牌时，怜执行碰或明杠而导致摸牌顺序改变时可出现
截图：
![tmp_11640-screenshot_2018-03-14-20-58-52-688_rolevax sakilogy3945751077678265657](https://user-images.githubusercontent.com/35923553/37404641-544edfbe-278a-11e8-9b1a-8dbe2b1bbfb2.png)

环境：0.9.3,Android 6.0.1

**Comment by rolevax** [comment]
设计如此
根据“牌山不变定律”，未来视操作可以错开被他家能力绝对收集的牌
