### ISSUE TITLE
打捞牌谱时按手机后退键会退出程序

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#184]
[松饼Bug]
ID: xmt
期望：打捞牌谱时按手机后退键会返回上一级
实际：打捞牌谱时按手机后退键会退出程序
复现步骤：打捞牌谱时按手机后退键
截图：
![qq 20180318142932](https://user-images.githubusercontent.com/36924637/37563580-fc150b2e-2abe-11e8-8686-9e54638b466a.jpg)
环境：0.9.3,Android 6.0.1

**Comment by rolevax** [comment]
+100
