### ISSUE TITLE
联机（包括牌谱）立直牌不横置

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#189]
[松饼Bug]
ID: xmt
期望：立直牌横置
实际：立直牌不横置
复现步骤：联机对战
截图：
![qq 20180319205458](https://user-images.githubusercontent.com/36924637/37654008-aac98132-2c7b-11e8-8c10-294444c7cfff.jpg)
环境：0.9.3,Android 6.0.1

**Comment by xiaomiantan3** [comment]
顺便问个问题，现在是不是不能用qq与您联系了？

**Comment by rolevax** [comment]
+100
