### ISSUE TITLE
文字会超出框

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#193]
[松饼Bug]
ID: xmt
期望：文字不会超出框
实际：文字会超出框
复现步骤：使用役种生成器，选13翻
截图：
![default](https://user-images.githubusercontent.com/36924637/37700505-c5e69166-2d26-11e8-9cb9-fd065d7a7292.PNG)
环境：0.9.3,Ubuntu 17.10

**Comment by rolevax** [comment]
+100
