### ISSUE TITLE
未来视立直时可能卡住

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#195]
[松饼Bug]
ID: xmt
期望：程序不会卡住
实际：程序卡住
复现步骤：使用园城寺怜，在未来视立直时可能卡住
截图：
![qq 20180321185005](https://user-images.githubusercontent.com/36924637/37705915-8490f172-2d38-11e8-868f-0dcfa822e8fb.jpg)
![qq 20180321185011](https://user-images.githubusercontent.com/36924637/37705916-859b9cf2-2d38-11e8-90b2-46be77714b51.jpg)
环境：0.9.3,Android 6.0.1

**Comment by rolevax** [comment]
10
