### ISSUE TITLE
手役生成器生成错误

### ISSUE THREAD

**Issue by cattaria** [rolevax/mjpancake#196]
[松饼Bug]
ID: Once
期望：选择4翻满贯时生成四翻满贯的牌
实际：选择4翻满贯时会有一定概率生成30符四翻的牌
复现步骤：选择并生成4翻满贯
截图：
![default](https://user-images.githubusercontent.com/10678783/37769324-9ca19a7c-2e0b-11e8-8036-329d1b783395.png)
环境：0.9.3 Windows 8.1

**Comment by rolevax** [comment]
50
