### ISSUE TITLE
怜在使用未来视时卡死

### ISSUE THREAD

**Issue by netyzh** [rolevax/mjpancake#198]
ID: netyzh
期望：怜在使用未来视时程序正常
实际：怜在使用未来视时程序卡死
复现步骤：由于怜在使用未来视时看到未和牌时一切正常，却从来没看到过自摸和牌的情况，推测怜未来视看到自摸和牌时会卡死。
截图：
![screenshot_2018-04-08-09-20-40](https://user-images.githubusercontent.com/38396687/38777311-59a1e00a-4095-11e8-831b-767745de8941.png)

环境：0.9.4, Android 6.0

**Comment by rolevax** [comment]
200

**Comment by chouqiandaren** [comment]
ID：羡ましい
卡死+1
![screenshot_20180530-205710](https://user-images.githubusercontent.com/35923553/40721674-cb928b80-644c-11e8-816c-524c27433ec6.jpg)
0.9.5, Android 8.1

**Comment by rolevax** [comment]
预计于 0.9.6 修复
