### ISSUE TITLE
v0.9.6 not Working on macOS after Building

### ISSUE THREAD

**Issue by uetcis** [rolevax/mjpancake#200]
**复现步骤**
通过以下操作，可以再次看到这个 bug：
1. git clone
2. git checkout
3. 用 Qt Creator 打开，设置目标为 macOS，build
4. 运行编译目录下生成的 .app 文件，没有任何窗口，直接提示无响应

**期望现象**
我本来期望这时能够开开心心地打麻将

**截图**
![Application Not Responding](https://i.imgur.com/bt9YYY9.jpg)

**环境**
- 系统：macOS Mojave 10.14.2 Developer Beta, Qt 5.11.0
- 版本：0.9.6

**Comment by rolevax** [comment]
窝手头没有 mac 机器，所以没法直接帮上忙
以前的确是曾经在 mac 上成功运行过的
可以尝试用 Qt Creator 的调试器搞一下，看看有没有线索

**Comment by uetcis** [comment]
hmmmm
我个人不熟悉 Qt 和 CPP

**Comment by rolevax** [comment]
> hmmmm
> 我个人不熟悉 Qt 和 CPP

用 Qt Creator 打开，点最左下角的 debug 按钮
后面出现的调试器界面和其它工具/语言大同小异
只要能有一点线索就行（手动doge

**Comment by uetcis** [comment]
现在再试又可以了，惊了
玄学问题

**Comment by uetcis** [comment]
但是还有个问题，iOS和macOS上编译出来不显示人物头像
