### ISSUE TITLE
iOS和macOS上编译出来不显示人物头像

### ISSUE THREAD

**Issue by rolevax** [rolevax/mjpancake#201]
_Originally posted by @CaptainYukinoshitaHachiman in https://github.com/rolevax/mjpancake/issues/200#issuecomment-441242053_

**Comment by rolevax** [comment]
@CaptainYukinoshitaHachiman

- 所有的人物都是默认不带头像的，需要自己手动设置
  - 是未设置过，还是设置过后不显示？

**Comment by uetcis** [comment]
是 设置 -> 头像 吗？选好人物后按中间的矩形不会弹出选照片的页面

**Comment by rolevax** [comment]
想起来了，iOS上没做这个功能
如果mac也不弹的话就是bug了

**Comment by uetcis** [comment]
mac上是有的
