### ISSUE TITLE
整理久帝听牌确定前最后一切时的各选项所听张数

### ISSUE THREAD

**Issue by rolevax** [rolevax/mjpancake#25]
任务内容：

- 完整收录久帝迄今为止的所有听牌确定前最后一切时各选项的视野内所听张数
- 牌河可见时，“张数”考虑牌河；牌河不可见时，注明牌河不可见，“张数”只看手牌
- 收集对象为“听牌”而非“和牌”，听了没和的也要包含在内

每条统计都仿照此例整理：
```
县预选决赛东一局
- 选项1：36958p，16张
- 选项2：1m，1张
```

提交方式：下方回复

验收通过条件：数据完整，无明显遗漏或错误

如有任何疑问，及时联络

**Comment by 346616338** [comment]
县预选决赛前半战东一局
- 选项1：36958p，16张
- 选项2：1m，2张
县预选决赛前半战东二局
- 选项1：25847s，16张
- 选项2：5p，1张
县预选决赛前半战东二局一本场 牌河不可见
- 选项1：258p8s，10张
- 选项2：7s，4张
县预选决赛后半战南二局
- 选项1：36p，8张
- 选项2：4m，0张
全国二回战前半战南三局一本场
- 选项1：5m，3张
- 选项2：7m东，3张
全国二回战前半战南四局
- 选项1：3689s，12张
- 选项2：467m，12张
全国二回战后半战南四局 
- 选项1：5m，2张
- 选项2：5p，3张
全国三回战前半战南二局 牌河不可见
- 选项1：36p，6张
- 选项2：14p，4张
全国三回战前半战南三局 牌河不可见
- 选项1：346s，11张
- 选项2：1s，3张
全国三回战后半战东一局 牌河不可见
- 选项1：467p，11张
- 选项2：7p，4张
全国三回战后半战东四局
- 选项1：7s，3张
- 选项2：36m，6张
全国三回战后半战南一局 牌河不可见
- 选项1：12567p，15张
- 选项2：南，3张

**Comment by I-sakisan** [comment]
更正几个。。。
县预选决赛前半战东一局
选项1:36958p，16张
选项2:1m，1张

全国二回战前半战南三局一本场，牌河仅部分可见
选项1：58m，7张
选项2：7m东，3张

全国二回战前半战南四局
选项1：3689s，12张
选项2：467m，11张

全国三回战前半战南二局 牌河仅部分可见
选项1：36p，6张
选项2：1p，4张

（补漏）全国三回战后半战东二局 牌河仅部分可见
选项1:7p，3张
选项2:8p，3张
选项3:69p，8张

全国三回战后半战南一局 牌河不可见
选项1：14725p，17张
选项2：南，3张
