### ISSUE TITLE
改良场上点棒的表示

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#36]
[已有功能改良]
ID: TerryHu
已有不足：如图，场上点棒较多时，点棒会遮挡角色名字和头像
![2017-12-23 18-59-18](https://user-images.githubusercontent.com/28784198/34319146-64165e22-e815-11e7-91d0-416acb3cfa21.png)
而且场上点棒达到一定程度时会显示不出来（东一局四本场+3立直棒，实际只显示出2立直棒，牌谱看不出），另外希望能在查看牌谱时也显示出场上点棒
改良方案：用数字的形式表示点棒
参考作品：天凤

**Comment by rolevax** [comment]
- 没草图（手动滑稽
- 挡名字是设计，制造压迫感，按住头像会隐藏场棒

**Comment by humuyan** [comment]
但是点棒较多时显示的数量不对啊。。。

**Comment by rolevax** [comment]
那可能是个新bug，
每次都会出现吗？

**Comment by humuyan** [comment]
> 东一局四本场+3立直棒，实际只显示出2立直棒

目前只记得这次了。。。之前好像出现过本场数较大（达到8左右）时本场棒的显示不正确
