### ISSUE TITLE
AI的一些行为

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#37]
[AI]
ID: TerryHu
角色：松实玄
期望表现：在摸完所有宝牌前不会轻易立直
实际表现：在摸完所有宝牌前听牌即立直
截图：
![2017-12-26 20-17-00](https://user-images.githubusercontent.com/28784198/34356572-c978cc6c-ea79-11e7-82e6-c7119719d1db.png)
[松饼Bug]
ID: TerryHu
期望现象：丰音追立直后，先制立直者一发摸入铳牌
实际现象：丰音追玄的立直后，玄没有一发摸入铳牌
复现步骤：选丰音和玄有概率出现
截图：同上图
环境：0.9.1-alpha3, Ubuntu 17.10
***
[AI]
ID: TerryHu
角色：多久和李绪，但可能不限于该角色
期望表现：AL四位，见逃无法逆转顺位的铳牌
实际表现：AL四位未见逃无法逆转顺位的铳牌
截图：
![2017-12-26 20-23-45](https://user-images.githubusercontent.com/28784198/34356726-548bc7a4-ea7b-11e7-8bef-9aab7147d02a.png)

**Comment by rolevax** [comment]
1. AI不会根据能力默听+100
2. 发现“玄丢宝牌后能否被别人的能力塞回宝牌”的问题+100
3. AI没有顺位意识+100
