### ISSUE TITLE
诚哥三副露后的和牌巡目

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#38]
[能力改良]
ID: TerryHu
角色：亦野诚子
期望表现：三副露后五巡内必自摸
实际表现：三副露后五巡内未自摸，且和了牌并没有全部被他家扣住
原作依据：
![2017-12-28 21-40-04](https://user-images.githubusercontent.com/28784198/34412419-151fadc6-ec18-11e7-9c16-fe89b650b1b3.png)
偶然排除：
这是三副露巡目
![2017-12-28 21-40-30](https://user-images.githubusercontent.com/28784198/34412413-11ea898c-ec18-11e7-8e54-34584fdcf9bf.png)
若干巡过去了。。。
![2017-12-28 21-41-07](https://user-images.githubusercontent.com/28784198/34412416-137de186-ec18-11e7-9b50-e7e740f69af8.png)

**Comment by rolevax** [comment]
+10
诚哥的三副露特指碰，不算吃，这是公认的吧
