### ISSUE TITLE
0.9.1 发布贴设计

### ISSUE THREAD

**Issue by rolevax** [rolevax/mjpancake#39]
新发布贴的目标：
- 标题和松饼无关，能吸到人
- 正文主题不是松饼，而是自定的另一个主题
- 正文好玩
- 全文不介绍松饼，而是仿佛理所当然般地将松饼的截图或视频嵌入正文当中
- 诱导人禁不住回复“这是什么游戏？”

提交方式：
- 将草稿及松饼ID回复到本 issue 下
- 只提交文字即可，图片或视频的部分用“此处有图片”或“此处有视频”代替

验收通过标准：
- 主观判断

（同名副本任务每人限领一次）

**Comment by karkimira** [comment]
Id:karkimira
[入门麻学]浅谈乱打及小林的谋算
7周目漫画后，突然对乱打的牌局起了兴趣。随后点开了16话，看四暗局。
5m1p4s6p中9m9s北东4m,9p立直。
非门清的状态下基本上能看出是在做对对，在门清状态可以考虑四暗，防守可以考虑熟张。但是，乱打在前局打生牌点5200,这其实是乱打为了误导他家认为自己是新手，从而使对手看不出牌路，让高强度对手控不了场，效果堪比蛇神，这直接让真子的数据库超载爆炸，用超凡的控场把8000点的和牌用自己的能力变成雅库曼，对手因为之前乱打的计谋以为是偶然，因为人人都能役满（此处有截图）达到扮猪吃老虎的效果，这就是乱打的谋略，看勇者，调查了那么多的牌谱，肯定是乱打研究后才来控场的。
再谈合宿的绿一色（此处漫画58话截图）
注意，注意，这里小林只画了乱打的手牌，只能看见乱打的手牌和部分弃牌，这其实是小林的阴谋，想要在画完县决后来吹一波乱打，但是，动画表示乱打必须死，但还是用国士来刷了一波时髦，于是小林决定用二回战的真子的top来提升乱打的逼格，但为何乱打是新人，却知道国士，这也是小林未向我们解释的一个谜。之后设定出了个阿知贺，小林也用阿的合宿成果来体现，乱打才是天麻中，能靠常人眼中的一波乱打，王牌眼中的老谋深算，来无意将地位抬到魔物的能力者
