### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#40]
1. 为什么最新一次pull后显示为“第三方修改版”
2. 联机登录时经常连接错误
3. 很好奇联机toki的实现

**Comment by rolevax** [comment]
1. `develop`分支不是对外发布的版本，对外发布的版本都是tag
    - 为了防止有人随手打包发布的测试版被误解成正式版，默认显示成“第三方修改版”
2. 联机是未开放的功能
3. 由AI预测人类行为，舍弃100%准确性
