### ISSUE TITLE
用涩谷尧深发现的一些问题

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#42]
用涩谷尧深坐尾庄，在南4之前收集了足够的幺九牌，达到无限九九流局的效果。

[日麻规则报错]
ID: TerryHu
期望现象：All Last 中途流局发生时，亲家没有下庄的权利
实际现象：All Last 中途流局发生时，亲家有下庄的权利
截图：
![screenshot_2018-01-14-11-15-19-743_rolevax sakilogy](https://user-images.githubusercontent.com/28784198/34914451-0f6f7404-f94e-11e7-8f7b-39b78777de22.png)

[能力改良]
ID: TerryHu
角色：涩谷尧深
期望表现：只有在南4可以发动 harvest time
实际表现：西入后仍然会发动 harvest time
原作依据：原著中未明确说明西入后的情况，但西入后仍发动不符合常理
偶然排除：
![screenshot_2018-01-14-11-24-26-437_rolevax sakilogy](https://user-images.githubusercontent.com/28784198/34914453-12bfd8e2-f94e-11e7-9704-7c8ee6205f85.png)

**Comment by rolevax** [comment]
>期望现象：All Last 中途流局发生时，亲家没有下庄的权利

期望的依据是什么？

> 原作依据：原著中未明确说明西入后的情况，但西入后仍发动不符合常理

“不符合常理”怎讲？

**Comment by humuyan** [comment]
第一条的依据见[此贴](https://tieba.baidu.com/p/3905436183?red_tag=2533919063)4楼
关于第二条，显然西场每一局起手都能有之前收集的牌不大好吧。。。

**Comment by rolevax** [comment]
> 第一条的依据见此贴4楼

+200，以后会添加“中途流局无条件连庄”规则

> 关于第二条，显然西场每一局起手都能有之前收集的牌不大好吧。。

哪里“显然”了？
（现在的西入是突然死亡式的，每一局都是all last）
