### ISSUE TITLE
关于京太郎的能力问题

### ISSUE THREAD

**Issue by humuyan** [rolevax/mjpancake#43]
[能力改良]
ID: TerryHu
角色：须贺京太郎
期望表现：京太郎的牌运差，对日麻规则没有完全了解，基本不会弃胡一类的操作
实际表现：京太郎的手牌进展速度甚至可以超过其他人物，在有人立直后破一发弃胡的技巧十分娴熟，与其他AI对战时完全不落下风
原作依据：一开始与saki等人对战都是垫底，并且经常点炮
偶然排除：
![screenshot_2018-01-14-17-16-21](https://user-images.githubusercontent.com/28784198/34914634-4b71a488-f951-11e7-8e2e-234b9619f287.png)
进行了多次对战，京太郎的排名基本都能比其他角色高，立直巡目很早，他家进攻时的弃胡也很强。
建议把京太郎的AI与其他人物的AI区分开写，貌似现在基础雀力部分京太郎和其他人物都是一样的？并且有必要限制一下京太郎的进张。天麻中不同人物的基础雀力还是有一定差异的，后续可以考虑写几个不同水平的基础雀力AI分配给不同的角色。

**Comment by rolevax** [comment]
+100

- 目前的京狗实现是“正常麻将”的参考基准，暂不打算还原原作中的倒霉成分
    - 解决问题的最简单办法是修改京太郎的显示名，比如改成“路人”
- “AI分级”如果有人做的话我支持
