### ISSUE TITLE
输入框越界

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#53]
[松饼Bug]
ID: xmt
期望现象：合理处理越界问题
实际现象：有字符在输入框外显示
复现步骤：在输入框内输入大量字符
截图：
![qq 20180228220752](https://user-images.githubusercontent.com/36924637/36822376-b2d4ca56-1d32-11e8-8b63-fde24b4cfdc2.jpg)
环境：0.9.1,Android 6.0.1

**Comment by rolevax** [comment]
100
