### ISSUE TITLE
下拉列表失去焦点时不消失

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#54]
[松饼Bug]
ID: xmt
期望现象：第二次选择后前一个框会消失
实际现象：第二次选择后前一个框不会消失
复现步骤：从下往上依次选择角色
截图：
![_20180228_205246](https://user-images.githubusercontent.com/36924637/36830564-18fe5ef6-1d5f-11e8-828d-b61d83d7ebe2.jpg)
环境：0.9.1,Android 6.0.1

**Comment by rolevax** [comment]
+100

旧贴第150楼”银“发过这个，不过因为楼被炸了就不算重复了

另外今天更新了有关反垄断的约定：https://mjpancake.github.io/feedback/
