### ISSUE TITLE
摸打练习时仍检查角色重复的bug

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#56]
[松饼Bug]
ID: xmt
期望现象：可以开始
实际现象：不能开始
复现步骤：选择除须贺京太郎的相同角色，选择摸打练习，点击“开始”
截图：
![qq 20180302221728](https://user-images.githubusercontent.com/36924637/36903501-dd448790-1e68-11e8-8dbf-1b11141831f1.jpg)
环境：0.9.1,Android 6.0.1

**Comment by rolevax** [comment]
100
