### ISSUE TITLE
牌谱牌局数较多时无法选择靠后的局

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#60]
[松饼Bug]
ID: xmt
期望现象：可以通过滑动查看各局
实际现象：无法选择靠后的局
复现步骤：打开场次较多的牌谱
截图：
![qq 20180303154534](https://user-images.githubusercontent.com/36924637/36931840-e7abf100-1ef9-11e8-94dc-1db45328b2d4.jpg)
环境：0.9.1,Android 6.0.1

**Comment by rolevax** [comment]
100
