### ISSUE TITLE
首页名单部分名字重叠

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#62]
[松饼Bug]
ID: xmt
期望现象：显示正常
实际现象：有部分名字重叠
复现步骤：打开贡献者名单页面
截图：
![qq 20180303170017](https://user-images.githubusercontent.com/36924637/36932481-75ffaa5a-1f04-11e8-8b54-887a0fbb1c15.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
