### ISSUE TITLE
背景预览界面牌局演示消失

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#63]
[松饼Bug]
ID: xmt
期望现象：正常显示牌局
实际现象：牌局无法显示
复现步骤：打开背景选项
截图：
![qq 20180303170545](https://user-images.githubusercontent.com/36924637/36932533-2eab982a-1f05-11e8-9c54-2587b57d142c.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
