### ISSUE TITLE
手役生成器非阻塞化

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#66]
[松饼Bug]
ID: xmt
期望现象：少女做牌时返回键可用
实际现象：少女做牌时返回键不可用
复现步骤：手役生成器生成较稀有的番
截图：
![qq 20180304132010](https://user-images.githubusercontent.com/36924637/36942514-d8b45f2e-1fae-11e8-9b07-96e3f2ffb41c.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
