### ISSUE TITLE
爆无duang

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#72]
[松饼Bug]
ID: xmt
期望现象：爆发时显示“duang”
实际现象：爆发前没有显示“duang”
复现步骤：使用上重漫
截图：无法通过截图体现
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
50
看看还有没有其它人遇到

**Comment by xiaomiantan3** [comment]
我用ubuntu试了一下，发现还是没duang
