### ISSUE TITLE
保存用户名和密码

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#86]
[松饼Bug]
ID: xmt
期望现象：再次登录会保存用户名和密码
实际现象：再次登录需重新输入用户名和密码
复现步骤：再次登录
截图：
![qq 20180305182239](https://user-images.githubusercontent.com/36924637/36970072-41430d9e-20a2-11e8-814e-b8b616971721.jpg)
![qq 20180305182244](https://user-images.githubusercontent.com/36924637/36970076-42af7910-20a2-11e8-9a22-d829951d187d.jpg)
环境：0.9.2,Android 6.0.1
不知道为什么，重装都没有用。

**Comment by rolevax** [comment]
100
