### ISSUE TITLE
牌形分解器中同种牌超过4张

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#88]
[松饼Bug]
ID: xmt
期望现象：牌形分解器中同种牌超过4张会报错
实际现象：牌形分解器中同种牌超过4张不会报错
复现步骤：在牌形分解器中输入超过4张相同的牌
截图：
![_20180305_184306](https://user-images.githubusercontent.com/36924637/36970920-227d9cb4-20a5-11e8-9af8-7a64d3d8e739.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
