### ISSUE TITLE
切换应用后UI异常

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#89]
[松饼Bug]
ID: xmt
期望现象：框的大小显示正常
实际现象：框的大小显示异常
复现步骤：进入牌形分解器后召唤出框，开一个竖屏软件后返回
截图：
![qq 20180305184800](https://user-images.githubusercontent.com/36924637/36971218-0c478954-20a6-11e8-9e61-6aafe49f00a2.jpg)
环境：0.9.2,Android 6.0.1
并不只是主界面有问题，各种和屏幕大小形状有关的框都有可能放大以后无法自己调整回来。

**Comment by rolevax** [comment]
200
