### ISSUE TITLE
显示当前桌数

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#95]
[松饼Bug]
ID: xmt
期望现象：对局桌数显示正常数字
实际现象：对局桌数显示问号
复现步骤：踩地板
截图：
![qq 20180305210657](https://user-images.githubusercontent.com/36924637/36976605-2c853622-20b9-11e8-9e97-29c85739c4c0.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
