### ISSUE TITLE
关服后继续预约

### ISSUE THREAD

**Issue by xiaomiantan3** [rolevax/mjpancake#96]
[松饼Bug]
ID: xmt
期望现象：关服后自动停止预约
实际现象：关服后继续预约
复现步骤：关服时保持预约状态
截图：
![qq 20180305213335](https://user-images.githubusercontent.com/36924637/36977683-ef5f42f2-20bc-11e8-8488-095ebec287c0.jpg)
环境：0.9.2,Android 6.0.1

**Comment by rolevax** [comment]
100
